### ISSUE TITLE
Does not run on TeamCity 9.1.7

### ISSUE THREAD

**Issue by jcox10** [grundic/teamcity-agent-priority#2]
Getting an exception when trying to add the plugin to our 9.1.7:

`[2017-02-03 15:11:20,509]   WARN - tion.CachingBuildEstimator$2$1 - Failed to execute Build estimates updater. jetbrains.buildServer.serverSide.SProject.getOwnFeaturesOfType(Ljava/lang/String;)Ljava/util/Collection; 
java.lang.NoSuchMethodError: jetbrains.buildServer.serverSide.SProject.getOwnFeaturesOfType(Ljava/lang/String;)Ljava/util/Collection;
	at com.github.grundic.agentPriority.manager.AgentPriorityManager.configuredForProject(AgentPriorityManager.java:97)
	at com.github.grundic.agentPriority.manager.AgentPriorityManager.configuredForProjectWithParents(AgentPriorityManager.java:129)
	at com.github.grundic.agentPriority.manager.AgentPriorityManager.sort(AgentPriorityManager.java:61)
	at com.github.grundic.agentPriority.buildDistribution.PriorityAgentsFilter.filterAgents(PriorityAgentsFilter.java:71)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.DefaultAgentsFilter.filterAgents(DefaultAgentsFilter.java:21)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildAgentDistributor.filterAvailableAgents(BuildAgentDistributor.java:17)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.AbstractDistributor.doDistribute(AbstractDistributor.java:35)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.DefaultBuildDistributor.assignBuildsToAgents(DefaultBuildDistributor.java:6)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildDistributorProxy.assignBuildsToAgents(BuildDistributorProxy.java:10)
	at jetbrains.buildServer.serverSide.impl.timeEstimation.DefaultBuildEstimatesCalculator.estimateBuilds(DefaultBuildEstimatesCalculator.java:109)
	at jetbrains.buildServer.serverSide.impl.timeEstimation.DefaultBuildEstimatesCalculator.estimateBuilds(DefaultBuildEstimatesCalculator.java:42)
	at jetbrains.buildServer.serverSide.impl.BuildEstimatorFeeder.getEstimates(BuildEstimatorFeeder.java:2)
	at jetbrains.buildServer.serverSide.impl.timeEstimation.CachingBuildEstimator.computeEstimates(CachingBuildEstimator.java:87)
	at jetbrains.buildServer.serverSide.impl.timeEstimation.CachingBuildEstimator$2$1.run(CachingBuildEstimator.java:1)
	at jetbrains.buildServer.util.ExceptionUtil$1.run(ExceptionUtil.java:41)
	at jetbrains.buildServer.serverSide.impl.timeEstimation.CachingBuildEstimator$2.run(CachingBuildEstimator.java:9)
	at java.lang.Thread.run(Unknown Source)`

`[2017-02-03 15:13:22,804]   WARN - verSide.impl.BuildServerRunner - Unexpected exception occurred in Flush Queue 1, operation will be repeated 
java.lang.NoSuchMethodError: jetbrains.buildServer.serverSide.SProject.getOwnFeaturesOfType(Ljava/lang/String;)Ljava/util/Collection;
	at com.github.grundic.agentPriority.manager.AgentPriorityManager.configuredForProject(AgentPriorityManager.java:97)
	at com.github.grundic.agentPriority.manager.AgentPriorityManager.configuredForProjectWithParents(AgentPriorityManager.java:129)
	at com.github.grundic.agentPriority.manager.AgentPriorityManager.sort(AgentPriorityManager.java:61)
	at com.github.grundic.agentPriority.buildDistribution.PriorityAgentsFilter.filterAgents(PriorityAgentsFilter.java:71)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.DefaultAgentsFilter.filterAgents(DefaultAgentsFilter.java:21)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildAgentDistributor.filterAvailableAgents(BuildAgentDistributor.java:17)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.AbstractDistributor.doDistribute(AbstractDistributor.java:35)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.DefaultBuildDistributor.assignBuildsToAgents(DefaultBuildDistributor.java:6)
	at jetbrains.buildServer.serverSide.impl.buildDistribution.BuildDistributorProxy.assignBuildsToAgents(BuildDistributorProxy.java:10)
	at jetbrains.buildServer.serverSide.impl.FlushQueueForConnectedAgents.distribute(FlushQueueForConnectedAgents.java:17)
	at jetbrains.buildServer.serverSide.impl.FlushQueueTemplate.flushRealAgents(FlushQueueTemplate.java:25)
	at jetbrains.buildServer.serverSide.impl.FlushQueueTemplate.access$100(FlushQueueTemplate.java:9)
	at jetbrains.buildServer.serverSide.impl.FlushQueueTemplate$2.run(FlushQueueTemplate.java:2)
	at jetbrains.buildServer.serverSide.impl.FlushQueueAction$QueueAction.run(FlushQueueAction.java:6)
	at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupState.runUnderLock(ServerCleanupState.java:37)
	at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupState.runReadAction(ServerCleanupState.java:14)
	at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupManagerImpl.executeWithInactiveCleanup(ServerCleanupManagerImpl.java:141)
	at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupManagerImpl$$FastClassBySpringCGLIB$$ba2c8525.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:708)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at jetbrains.buildServer.serverSide.impl.auth.TeamCityMethodSecurityInterceptor.invoke(TeamCityMethodSecurityInterceptor.java:7)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$FixedChainStaticTargetInterceptor.intercept(CglibAopProxy.java:594)
	at jetbrains.buildServer.serverSide.impl.cleanup.ServerCleanupManagerImpl$$EnhancerBySpringCGLIB$$b6975960.executeWithInactiveCleanup(<generated>)
	at jetbrains.buildServer.serverSide.impl.QueueFlushImpl.flushQueue(QueueFlushImpl.java:10)
	at jetbrains.buildServer.serverSide.impl.BuildServerImpl.flushQueue(BuildServerImpl.java:168)
	at jetbrains.buildServer.serverSide.impl.BuildServerRunner$2.doSomething(BuildServerRunner.java)
	at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.runAction(BuildServerRunner.java:47)
	at jetbrains.buildServer.serverSide.impl.BuildServerRunner$BuildServerWorker.run(BuildServerRunner.java:9)
	at java.lang.Thread.run(Unknown Source)`

**Comment by grundic** [comment]
Hello!

The plugin was developed as part of Teamcity plugin contest 2016 and uses some API methods, that were introduced only in version 10.
You have to upgrade your version of Teamcity, then it would work fine.

**Comment by jcox10** [comment]
Ok thanks! I didn't see any version mentioned, so I thought I would try. I
am trying to get my work to buy a new enterprise licence so I can upgrade
to v10, but it's a slow process.

**Comment by grundic** [comment]
I will add a version requirements to the README file, so it would be more clear.
Yes, I know how difficult it could be to get an update for a software.. 
Though, JetBrains add a lot of new features in that release, so I hope you can get that approved!
